version: "3.9"

services:

  backend:
    build: .
    container_name: analytics-backend
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_BACKEND: rpc://

      # CLICKHOUSE CLOUD
      CLICKHOUSE_HOST: zvx41wbk0r.asia-northeast1.gcp.clickhouse.cloud
      CLICKHOUSE_PORT: 8443
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "w3uqO75Wq_29r"
      CLICKHOUSE_SECURE: "true"

    depends_on:
      rabbitmq:
        condition: service_started

    command: >
      sh -c "
        python backend/db/database.py &&
        python backend/db/aggregation_init.py &&
        uvicorn backend.main:app --host 0.0.0.0 --port 8000
      "

  worker:
    build: .
    container_name: analytics-worker
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    command: celery -A backend.celery_app.celery worker --loglevel=info

    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_BACKEND: rpc://

      # CLICKHOUSE CLOUD
      CLICKHOUSE_HOST: zvx41wbk0r.asia-northeast1.gcp.clickhouse.cloud
      CLICKHOUSE_PORT: 8443
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "w3uqO75Wq_29r"
      CLICKHOUSE_SECURE: "true"

    depends_on:
      rabbitmq:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  superset:
    container_name: superset
    build:
      context: ./superset
    restart: always
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_CONFIG_PATH: /app/superset_config.py
    volumes:
      - ./superset_config.py:/app/superset_config.py
      - superset_data:/app/superset_home

    # Superset does NOT depend on local ClickHouse (Cloud only)
    depends_on:
      rabbitmq:
        condition: service_started

volumes:
  superset_data:
